server:
  port: 8083

properties:
  url:
    client-processing: "http://localhost:8081/api/v1/clients/"

  credit-limit: 10000000
  interest-rate: 0.20

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/credit-processing_db
    username: postgres
    password: Dima_2145
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      format_sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: client-credit-products-event
      properties:
        spring:
          json:
            trusted:
              packages: "my.lib.core"