server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/client-processing_db
    username: postgres
    password: Dima_2145
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      format_sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery:
          timeout:
            ms: 20000
        linger:
          ms: 0
        request:
          timeout:
            ms: 10000
    topics:
      client-products: client_products
      client-credit-products: client_credit_products
      client-cards: client_cards
      client-transactions: client_transactions
      client-payments: client_payments
